### ISSUE TITLE
Inscribed a text file but getting weird output on Ordinals.com

### ISSUE THREAD

**Issue by skyrover7** [supertestnet/inscriptions-online#1]
I minted the attached file. 

[test2.txt](https://github.com/supertestnet/inscriptions-online/files/10975138/test2.txt)

It shows like this on ordinals.com site and content link
* https://ordinals.com/inscription/fe30f830a8996911c13f7cb7c77c6b686aae64d7d7536ee14e24e32c90a5de05i0
* https://ordinals.com/content/fe30f830a8996911c13f7cb7c77c6b686aae64d7d7536ee14e24e32c90a5de05i0

However i have minted similar text using other services and got this
* https://ordinals.com/inscription/5aa99dfb615db7b49d304adef5e307b1056c00feeea93455469f9c71046387cai0
* https://ordinals.com/content/5aa99dfb615db7b49d304adef5e307b1056c00feeea93455469f9c71046387cai0

All that being said, it looks like the file previews ok on ordinals wallet 🤔 . I don't see anything in the code that would not preserve the encoding?

**Comment by skyrover7** [comment]
Maybe this is ordinals.com being problematic, not sure

**Comment by skyrover7** [comment]
@supertestnet it looks like the mimetype for text files is expected to include the charset for ordinals.com to properly process it. not a hug deal, but i added a small check to accommodate

```js
if(file.type =='text/plain'){
    sessionStorage[ "mimetype" ] = 'text/plain;charset=utf-8'
}
else{
    sessionStorage[ "mimetype" ] = file.type;
}
```

**Comment by supertestnet** [comment]
Hi Aneesh, sorry I didn't see this til now. Thank you for opening this issue! I'm glad we came to the same solution. I also just integrated a built-in tool for inscribing domain names so this should be basically fully automated now: https://inscribetheplanet.com/
