### ISSUE TITLE
Batch minting

### ISSUE THREAD

**Issue by skyrover7** [supertestnet/inscriptions-online#3]
@supertestnet is batch minting a set of files in the roadmap? 🙏🏾

**Comment by skyrover7** [comment]
@supertestnet my understanding is that you would need to create multiple inputs from the user's invoice payment, and then use each one of those inputs once the payment has been confirmed. 

With bitcoin-cli this is achieved using the sendmany command to essentially create x number of inputs that can be used for inscriptions in one transaction. I'm not sure what the equivalent looks like here, but thought to share!

**Comment by BennyTheDev** [comment]
batchminting is working in my most recent PR https://github.com/supertestnet/inscriptions-online/pull/4

**Comment by supertestnet** [comment]
Batch minting is merged and is now live
